@Library('existing-build-control')
import static com.r3.build.BuildControl.killAllExistingBuildsForJob
killAllExistingBuildsForJob(env.JOB_NAME, env.BUILD_NUMBER.toInteger())

pipeline {

    agent {
        dockerfile {
            filename '.ci/staging/Dockerfile'
            additionalBuildArgs "--build-arg USER=stresstester"
            args '-v /var/run/docker.sock:/var/run/docker.sock --group-add 999'
        }
    }

    options { timestamps() }

    environment {
        ARTIFACTORY_CREDENTIALS = credentials('artifactory-credentials')
        DOCKER_CREDENTIALS = credentials('payments-docker-credentials')
        DOCKER_REGISTRY = "r3payments.azurecr.io"
        DOCKER_PUSH_USERNAME = $DOCKER_CREDENTIALS_USR
        DOCKER_PUSH_PASSWORD = $DOCKER_CREDENTIALS_PSW
        LOOPBACK_ADDRESS = "172.17.0.1"
    }

    stages {

        stage('Unit Tests') {
            steps {
                sh "./gradlew test"
            }
         }

        stage('Integration Tests') {
            steps {
                sh "./gradlew integrationTest"
            }
        }

        stage('Docker image pull for freighter') {
            steps {
                timeout(60) {
                    sh '''
                        docker pull postgres:9.6
                        docker pull roastario/freighter-base:latest
                        docker pull roastario/notary-and-network-map:4.0
                        '''
                }
            }
        }

        stage('Freighter Tests') {
            steps {
                timeout(60) {
                    sh '''
                        export ARTIFACTORY_USERNAME=\"\${ARTIFACTORY_CREDENTIALS_USR}\"
                        export ARTIFACTORY_PASSWORD=\"\${ARTIFACTORY_CREDENTIALS_PSW}\"
                        ./gradlew --parallel -Pfreighter.forks=2 freighterTest --info --stacktrace --no-daemon
                        '''
                }
            }
        }

        stage('Create and push docker images') {
            steps {
                sh "./gradlew createAndPushDockerImages"
            }
        }

        stage('Build Network Deployments') {
            steps {
                sh "./gradlew buildAllNetworks"
            }
        }

        //TODO: kubectl apply -f build/kubernetes/ledgerswaps.yaml
        stage('Deploy to Azure') {
            steps {
                withCredentials([azureServicePrincipal("payments-deployer-service-principal")]) {
                    sh '''
                    az login --service-principal -u $AZURE_CLIENT_ID -p $AZURE_CLIENT_SECRET -t $AZURE_TENANT_ID
                    az account set -s $AZURE_SUBSCRIPTION_ID
                    az aks get-credentials --resource-group payments-dev --name payments-dev-k8s
                    kubectl apply -f deploy/build/kubernetes/namespaceAndCredDeployment.yaml
                    kubectl apply -f deploy/build/kubernetes/auctionNetworkDeployment.yaml
                    kubectl apply -f deploy/build/kubernetes/gbpNetworkDeployment.yaml
                    kubectl apply -f deploy/build/kubernetes/cbdcNetworkDeployment.yaml
                  '''
                }
            }
        }

    }

    post {
        always {
            junit '**/build/test-results/**/*.xml'
            archiveArtifacts artifacts: '**/build/kubernetes/*.yaml'
        }

        cleanup {
            deleteDir() /* clean up our workspace */
        }
    }
}